name: 🧪 Run Tests

on:
  workflow_dispatch:  # Only runs manually from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

      - name: Run tests
        run: pytest
        env:
        CI: true  # ✅ makes os.getenv("CI") work inside Python